ALTER TABLE IF EXISTS "Course"
  ADD COLUMN IF NOT EXISTS "startDate" TIMESTAMP(6),
  ADD COLUMN IF NOT EXISTS "endDate" TIMESTAMP(6),
  ADD COLUMN IF NOT EXISTS "durationWeeks" INTEGER;

ALTER TABLE IF EXISTS "AttendanceSession"
  ADD COLUMN IF NOT EXISTS "isAutoGenerated" BOOLEAN NOT NULL DEFAULT FALSE;

UPDATE "AttendanceSession" AS attendance
SET "isAutoGenerated" = TRUE
FROM "Course" AS course
WHERE attendance."courseId" = course."id"
  AND attendance."startsAt" IS NULL
  AND attendance."endsAt" IS NULL
  AND attendance."title" LIKE course."title" || ' - %'
  AND NOT EXISTS (
    SELECT 1
    FROM "AttendanceRecord" AS record
    WHERE record."sessionId" = attendance."id"
  );
