import { prisma } from "@/lib/prisma";
import { getCourseAttendanceSessionDates, weekdayFromDate, weekdayLabel, type WeekdayValue } from "@/lib/attendance";

function formatAttendanceDateKey(date: Date) {
  return date.toISOString().slice(0, 10);
}

export async function ensureCourseAttendanceSessions({
  courseId,
  courseTitle,
  attendanceDays,
  startDate,
  durationWeeks,
  createdById,
}: {
  courseId: string;
  courseTitle: string;
  attendanceDays: WeekdayValue[];
  startDate: Date | null;
  durationWeeks: number | null;
  createdById: string;
}) {
  const scheduledDates =
    attendanceDays.length && startDate && durationWeeks
      ? getCourseAttendanceSessionDates(attendanceDays, startDate, durationWeeks)
      : [];
  const scheduledKeys = new Set(scheduledDates.map(formatAttendanceDateKey));

  const existingSessions = await prisma.attendanceSession.findMany({
    where: { courseId },
    select: {
      id: true,
      title: true,
      sessionDate: true,
      startsAt: true,
      endsAt: true,
      isAutoGenerated: true,
      _count: {
        select: { records: true },
      },
    },
  });

  const existingKeys = new Set(existingSessions.map((session) => formatAttendanceDateKey(session.sessionDate)));
  const automaticTitles = new Set(
    attendanceDays.map((day) => `${courseTitle} - ${weekdayLabel(day)}`),
  );
  const obsoleteSessionIds = existingSessions
    .filter((session) => {
      const isLegacyAutomatic =
        !session.isAutoGenerated &&
        !session.startsAt &&
        !session.endsAt &&
        session._count.records === 0 &&
        automaticTitles.has(session.title);

      return (
        (session.isAutoGenerated || isLegacyAutomatic) &&
        session._count.records === 0 &&
        !scheduledKeys.has(formatAttendanceDateKey(session.sessionDate))
      );
    })
    .map((session) => session.id);

  const sessionsToCreate = scheduledDates
    .filter((sessionDate) => !existingKeys.has(formatAttendanceDateKey(sessionDate)))
    .map((sessionDate) => ({
      courseId,
      createdById,
      title: courseTitle + " - " + weekdayLabel(weekdayFromDate(sessionDate) ?? ""),
      sessionDate,
      startsAt: null,
      endsAt: null,
      isAutoGenerated: true,
    }));

  await prisma.$transaction([
    prisma.attendanceSession.deleteMany({
      where: { id: { in: obsoleteSessionIds } },
    }),
    prisma.attendanceSession.createMany({
      data: sessionsToCreate,
      skipDuplicates: true,
    }),
  ]);
}
