import { getCourseAttendanceSessionDates, type WeekdayValue } from "@/lib/attendance";
import { parseLmsDateValue } from "@/lib/lmsTime";

const MAX_COURSE_DURATION_WEEKS = 260;

export function parseCourseDurationWeeks(value: string | number | null | undefined) {
  if (value === null || typeof value === "undefined" || value === "") {
    return null;
  }

  const durationWeeks = Number(value);
  return Number.isInteger(durationWeeks) ? durationWeeks : null;
}

export function parseCourseDate(value: string | null | undefined) {
  return value ? parseLmsDateValue(value) : null;
}

export function validateCourseSchedule({
  attendanceDays,
  startDate,
  endDate,
  durationWeeks,
}: {
  attendanceDays: WeekdayValue[];
  startDate: Date | null;
  endDate: Date | null;
  durationWeeks: number | null;
}) {
  if (!startDate || !endDate || !durationWeeks) {
    return "Course start date, end date, and duration in weeks are required.";
  }

  if (durationWeeks < 1 || durationWeeks > MAX_COURSE_DURATION_WEEKS) {
    return `Course duration must be between 1 and ${MAX_COURSE_DURATION_WEEKS} weeks.`;
  }

  if (endDate.getTime() < startDate.getTime()) {
    return "Course end date must be on or after the start date.";
  }

  const attendanceDates = getCourseAttendanceSessionDates(attendanceDays, startDate, durationWeeks);
  const lastAttendanceDate = attendanceDates.at(-1);

  if (lastAttendanceDate && lastAttendanceDate.getTime() > endDate.getTime()) {
    return "Course end date must include every attendance day generated by the selected duration.";
  }

  return null;
}
